POST http://localhost:3001/signup HTTP/1.1
content-type: application/json

{
	"email" : "juju@gmail.com",
	"password" : "juju",
	"firstname": "juju",
	"groupName": "Test1",
	"icon": "test"
}

###

PATCH  http://localhost:3000/update-widget/9 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZE1lbWJlciI6Mywicm9sZSI6MywiZ3JvdXBJZCI6MywiZmlyc3RuYW1lIjoiYmxhIiwiaWF0IjoxNjE5NDMyNTc3LCJleHAiOjE2MTk1MTg5Nzd9.OIg_og7FUM5WNbJ6GiIVpB9s3Nb-apX6vakYY6xpDmI

{
	"title": "updatedTitle", 
	"description": "updatedDescription",
	"groupMembers": []
}