-- MySQL Script generated by MySQL Workbench
-- Sun Apr 11 16:21:07 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

BEGIN;

DROP TABLE IF EXISTS "member" CASCADE;
DROP TABLE IF EXISTS "group" CASCADE;
DROP TABLE IF EXISTS "widget" CASCADE;
DROP TABLE IF EXISTS "label" CASCADE;
DROP TABLE IF EXISTS "field" CASCADE;
DROP TABLE IF EXISTS "member_widget" CASCADE;

-- -----------------------------------------------------
-- Table "member"
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS "member" (
  "id" SERIAL PRIMARY KEY,
  "firstname" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "password" TEXT NOT NULL,
  "role" TEXT NOT NULL,
  "icon" TEXT NOT NULL
 );

-- -----------------------------------------------------
-- Table "group"
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS "group" (
  "id" SERIAL PRIMARY KEY,
  "name" TEXT NOT NULL,
  "MEMBER_id_member" INT NOT NULL,
  PRIMARY KEY ("id_group"),
  INDEX "fk_GROUP_MEMBER_idx" ("MEMBER_id_member" ASC) VISIBLE,
  CONSTRAINT "fk_GROUP_MEMBER"
    FOREIGN KEY ("MEMBER_id_member")
    REFERENCES "MEMBER" ("id_member")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    );

-- -----------------------------------------------------
-- Table "widget"
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS "widget" (
  "id" SERIAL PRIMARY KEY,
  "list_styles" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "color" TEXT NOT NULL,
  "date" DATE NOT NULL
  );


-- -----------------------------------------------------
-- Table "field"
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS "field" (
  "id" SERIAL PRIMARY KEY,
  "description" TEXT NOT NULL,
  "checked" TINYINT NOT NULL,
  "WIDGET_id" INT NOT NULL,
  PRIMARY KEY ("id", "WIDGET_id"),
  INDEX "fk_FIELD_WIDGET1_idx" ("WIDGET_id" ASC) VISIBLE,
  CONSTRAINT "fk_FIELD_WIDGET1"
    FOREIGN KEY ("WIDGET_id")
    REFERENCES "WIDGET" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)

-- -----------------------------------------------------
-- Table "label"
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS "label" (
  "id" SERIAL PRIMARY KEY,
  "name" TEXT NOT NULL,
  "icon" TEXT NOT NULL,
  "WIDGET_id" INT NOT NULL,
  PRIMARY KEY ("id", "WIDGET_id"),
  INDEX "fk_LABEL_WIDGET1_idx" ("WIDGET_id" ASC) VISIBLE,
  CONSTRAINT "fk_LABEL_WIDGET1"
    FOREIGN KEY ("WIDGET_id")
    REFERENCES "WIDGET" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)

-- -----------------------------------------------------
-- Table "member_widget"
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS "member_widget" (
    "id" SERIAL PRIMARY KEY,
  "MEMBER_id_member" INT NOT NULL,
  "WIDGET_id" INT NOT NULL,
  PRIMARY KEY ("MEMBER_id_member", "WIDGET_id"),
  INDEX "fk_MEMBER_WIDGET_WIDGET1_idx" ("WIDGET_id" ASC) VISIBLE,
  INDEX "fk_MEMBER_WIDGET_MEMBER1_idx" ("MEMBER_id_member" ASC) VISIBLE,
  CONSTRAINT "fk_MEMBER_WIDGET_MEMBER1"
    FOREIGN KEY ("MEMBER_id_member")
    REFERENCES "MEMBER" ("id_member")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_MEMBER_WIDGET_WIDGET1"
    FOREIGN KEY ("WIDGET_id")
    REFERENCES "WIDGET" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)

COMMIT;